"""Backbone / pathway-recurrence reduction for pair-mode Incytr paths.

Reads the 9 contrast-level wide parquets from
``outputs/reports/incytr_pair_mode/wide/`` (one file per contrast),
applies the canonical significance floor (same as ``filter_significant_paths.py``),
and aggregates each unique path across contrasts into a ranked backbone table.

**Output schema** — ``outputs/reports/incytr_pair_mode/backbone/backbone_table.parquet``

Path identity columns (6-tuple, one row per unique path):

    Sender.group       VARCHAR  — sending cluster (Levy-t5 spine)
    Receiver.group     VARCHAR  — receiving cluster
    Ligand             VARCHAR
    Receptor           VARCHAR
    EM                 VARCHAR  — enzymatic mediator; NULL when absent from a path
    Target             VARCHAR  — final target; NULL when absent from a path

Recurrence / ranking columns:

    PDS                DOUBLE   — representative: signed PDS at the max-|PDS| occurrence
    n_timepoints_present  INTEGER — max, *over conditions*, of (distinct timepoints
                                    that condition appears in); measures within-genotype
                                    temporal stability (1–3).  A path at 2/4/6mo of App
                                    scores 3; a path scattered one-timepoint each across
                                    3 genotypes scores 1.
    n_conditions_present  INTEGER — number of distinct genotype conditions (1–3)
    backbone_rank      BIGINT   — dense rank: n_timepoints_present DESC →
                                  n_conditions_present DESC → |PDS| DESC;
                                  dense and gap-free (ties share the same rank).
    conditions_present VARCHAR  — comma-joined sorted condition labels, e.g. "App,Tau"
    contrasts_present  VARCHAR  — comma-joined sorted contrast labels,
                                  e.g. "App_2mo,App_4mo,Tau_2mo"

Annotation columns (NULL if annotation files not yet generated by ``pixi run snrna``):

    mean_gene_specificity  DOUBLE  — mean specificity_score over the ≤4 position genes
                                     present (Ligand looked up in Sender.group;
                                     Receptor/EM/Target in Receiver.group).  Empty
                                     positions and genes absent from the specificity
                                     file are excluded from the mean (not zeroed).
    min_cell_count         INTEGER — min n_cells over {Sender.group, Receiver.group},
                                     computed as the minimum over males-only (ma_*)
                                     samples.  Surfaces worst-case sparsity.

Flag columns:

    is_cholinergic_target  BOOLEAN — TRUE when Receiver.group == 'Cholinergic.Neurons';
                                      never filtered, only flagged (B2 display concern).

Backbone-key note
-----------------
Path identity is the full 6-tuple (locked decision, P3 grill 2026-06-25).  The
``--backbone-key`` argument exposes the parameterizable core for B4/B5
reconciliation at the W1 gate:

    full   (default)  — GROUP BY all 6 tuple columns (locked identity)
    l-r-em            — GROUP BY (Sender, Receiver, Ligand, Receptor, EM);
                         Target variants collapsed into Target_values
    r-em-t            — GROUP BY (Sender, Receiver, Receptor, EM, Target);
                         Ligand variants collapsed into Ligand_values
    r-em              — GROUP BY (Sender, Receiver, Receptor, EM);
                         both Ligand and Target collapsed

Non-full keys are provided for B4 reconciliation analysis only; the canonical
output uses ``full``.

Canonical floor (idempotent re-application)
-------------------------------------------
    (SigProb_<disease> > 0.1 OR SigProb_<WTyp> > 0.1) AND |PDS| >= 0.2

The wide parquets are unfiltered (driver emits all paths); the floor is
re-applied here to remain correct whether or not ``filter_significant_paths.py``
has run.  Raising the cutoffs is explicitly forbidden (CLAUDE.md).

Memory safety
-------------
All reduction runs through DuckDB (spill to ``DUCKDB_TEMP_DIR``, default
``~/.cache/duckdb``).  No whole-file pandas read of the wide parquets.
The specificity and cell-count CSVs are small (<1 MB) and read fully.
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys
import time
from pathlib import Path

import duckdb

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SIGPROB_CUTOFF: float = 0.1
ABS_PDS_CUTOFF: float = 0.2

_GENO_NORMALIZE: dict[str, str] = {
    "AppP": "App", "App": "App",
    "Ttau": "Tau", "Tau": "Tau", "TtauP": "Tau",
    "ApTt": "ApTt", "AppPTtau": "ApTt", "AppTtau": "ApTt",
}

# Columns that form the path identity under each backbone key.
_KEY_COLS: dict[str, tuple[str, ...]] = {
    "full":   ("Sender.group", "Receiver.group", "Ligand", "Receptor", "EM", "Target"),
    "l-r-em": ("Sender.group", "Receiver.group", "Ligand", "Receptor", "EM"),
    "r-em-t": ("Sender.group", "Receiver.group", "Receptor", "EM", "Target"),
    "r-em":   ("Sender.group", "Receiver.group", "Receptor", "EM"),
}

# All 4 position columns (after the 2 group columns).
_POSITION_COLS = ("Ligand", "Receptor", "EM", "Target")

_REPO_ROOT = Path(__file__).parent.parent.parent


# ---------------------------------------------------------------------------
# Filename parsing
# ---------------------------------------------------------------------------

_FNAME_RE = re.compile(
    r"ma_(\d+)mo_([A-Za-z]+)_ma_\1mo_WTyp_incytr_output\.parquet$"
)


def _parse_filename(fname: str) -> tuple[str, str, str] | None:
    """Return (contrast, condition, timepoint) or None if not parseable.

    ``ma_2mo_AppP_ma_2mo_WTyp_incytr_output.parquet`` → ``('App_2mo', 'App', '2mo')``
    """
    m = _FNAME_RE.match(os.path.basename(fname))
    if not m:
        return None
    age, geno_token = m.group(1), m.group(2)
    geno = _GENO_NORMALIZE.get(geno_token)
    if geno is None:
        return None
    contrast = f"{geno}_{age}mo"
    return contrast, geno, f"{age}mo"


def _detect_sigprob(con: duckdb.DuckDBPyConnection, path: str) -> tuple[str, str]:
    """Return the two ``SigProb_*`` column names for one wide parquet."""
    names = [r[0] for r in con.execute(
        f"DESCRIBE SELECT * FROM read_parquet('{path}') LIMIT 0"
    ).fetchall()]
    sigprob = sorted(n for n in names if n.startswith("SigProb_"))
    if len(sigprob) != 2:
        raise SystemExit(f"{path}: expected 2 SigProb_* cols, found {sigprob!r}")
    if "PDS" not in names:
        raise SystemExit(f"{path}: no PDS column")
    return sigprob[0], sigprob[1]


# ---------------------------------------------------------------------------
# SQL builder
# ---------------------------------------------------------------------------

def _q(col: str) -> str:
    """Double-quote a column name for DuckDB SQL."""
    return f'"{col}"'


def _build_backbone_query(
    files_info: list[tuple[str, str, str, str, str, str]],
    key_cols: tuple[str, ...],
    spec_path: str | None,
    counts_path: str | None,
) -> str:
    """Build the full DuckDB SQL string for backbone reduction + annotation.

    Parameters
    ----------
    files_info
        List of (abs_path, sp1, sp2, contrast, condition, timepoint) per file.
    key_cols
        Columns that form the path identity for this backbone_key.
    spec_path
        Absolute path to ``song_expression_specificity.csv`` or None.
    counts_path
        Absolute path to ``pseudobulk_cell_counts.csv`` or None.
    """
    # --- gated per-file subqueries ----------------------------------------
    file_parts: list[str] = []
    for abs_path, sp1, sp2, contrast, condition, timepoint in files_info:
        safe = abs_path.replace("'", "''")
        part = f"""
    SELECT
        "Sender.group", "Receiver.group",
        Ligand, Receptor, EM, Target, PDS,
        '{contrast}' AS contrast,
        '{condition}' AS condition,
        '{timepoint}' AS timepoint
    FROM read_parquet('{safe}')
    WHERE ({_q(sp1)} > {SIGPROB_CUTOFF} OR {_q(sp2)} > {SIGPROB_CUTOFF})
      AND ABS(PDS) >= {ABS_PDS_CUTOFF}"""
        file_parts.append(part)

    gated_union = "\n    UNION ALL".join(file_parts)

    # --- determine which position columns are extra (not in key) -----------
    key_set = set(key_cols)
    extra_pos = [c for c in _POSITION_COLS if c not in key_set]

    # Quoted key columns for SELECT / GROUP BY
    key_sel = ", ".join(_q(c) for c in key_cols)
    key_grp = key_sel  # same

    # Pre-build multi-line SQL fragments for extra position columns.
    # These are plain strings (not f-string expressions) so \n is fine.
    _sep2 = ",\n           "
    _sep4 = ",\n        "
    extra_agg_per_contrast = ""
    extra_agg_path = ""
    extra_sel_backbone = ""
    # Suffix for the final SELECT (precomputed to avoid \n inside f-string {}).
    extra_pos_select_suffix = ""
    if extra_pos:
        extra_agg_per_contrast = _sep2 + _sep2.join(
            f"STRING_AGG(DISTINCT {_q(c)}, '|' ORDER BY {_q(c)}) AS {_q(c + '_values')}"
            for c in extra_pos
        )
        extra_agg_path = _sep2 + _sep2.join(
            f"STRING_AGG({_q(c + '_values')}, '|' ORDER BY {_q(c + '_values')}) AS {_q(c + '_values')}"
            for c in extra_pos
        )
        extra_sel_backbone = _sep4 + _sep4.join(
            f"pp.{_q(c + '_values')}" for c in extra_pos
        )
        extra_pos_select_suffix = ",\n    " + ", ".join(
            _q(c + "_values") for c in extra_pos
        )

    # The backbone JOIN uses IS NOT DISTINCT FROM on each key column so that
    # NULL == NULL (EM/Target are nullable — USING join would silently drop them).
    backbone_join_cond = " AND\n        ".join(
        f"cs.{_q(c)} IS NOT DISTINCT FROM pp.{_q(c)}"
        for c in key_cols
    )

    # --- CTE chain --------------------------------------------------------
    #
    # per_contrast  : de-duplicate within each (6-tuple, file); one row per
    #                 (identity-key, contrast, condition, timepoint).
    # per_condition : per (identity-key, condition) → distinct timepoints.
    # cond_stats    : per identity-key → n_conditions, n_timepoints_present,
    #                 conditions_present string.
    # path_pds      : per identity-key → representative PDS, contrasts_present,
    #                 is_cholinergic_target.
    # backbone      : join cond_stats + path_pds.
    # ranked        : add dense_rank.
    # (optional) spec + cell_counts CTEs + final annotated SELECT.

    cq = f"""
WITH
gated AS ({gated_union}
),
per_contrast AS (
    SELECT
        {key_sel},
        contrast, condition, timepoint,
        ARG_MAX(PDS, ABS(PDS)) AS rep_pds{extra_agg_per_contrast}
    FROM gated
    GROUP BY {key_grp}, contrast, condition, timepoint
),
per_condition AS (
    SELECT
        {key_sel},
        condition,
        COUNT(DISTINCT timepoint) AS n_tp
    FROM per_contrast
    GROUP BY {key_grp}, condition
),
cond_stats AS (
    SELECT
        {key_sel},
        COUNT(*) AS n_conditions_present,
        MAX(n_tp) AS n_timepoints_present,
        STRING_AGG(condition, ',' ORDER BY condition) AS conditions_present
    FROM per_condition
    GROUP BY {key_grp}
),
path_pds AS (
    SELECT
        {key_sel},
        ARG_MAX(rep_pds, ABS(rep_pds)) AS PDS,
        STRING_AGG(contrast, ',' ORDER BY contrast) AS contrasts_present,
        BOOL_OR("Receiver.group" = 'Cholinergic.Neurons') AS is_cholinergic_target{extra_agg_path}
    FROM per_contrast
    GROUP BY {key_grp}
),
backbone AS (
    SELECT
        {", ".join("cs." + _q(c) for c in key_cols)},
        pp.PDS,
        cs.n_timepoints_present::INTEGER AS n_timepoints_present,
        cs.n_conditions_present::INTEGER AS n_conditions_present,
        cs.conditions_present,
        pp.contrasts_present,
        pp.is_cholinergic_target{extra_sel_backbone}
    FROM cond_stats cs
    JOIN path_pds pp ON ({backbone_join_cond})
),
ranked AS (
    SELECT *,
        DENSE_RANK() OVER (
            ORDER BY n_timepoints_present DESC,
                     n_conditions_present DESC,
                     ABS(PDS) DESC
        ) AS backbone_rank
    FROM backbone
)"""

    # --- annotation CTEs (optional) ---------------------------------------
    if spec_path is not None and counts_path is not None:
        safe_spec = spec_path.replace("'", "''")
        safe_counts = counts_path.replace("'", "''")

        if "full" in str(key_cols):  # only meaningful for full 6-tuple key
            mean_spec_expr = """(
            COALESCE(CASE WHEN spec_l.specificity_score IS NOT NULL THEN spec_l.specificity_score ELSE NULL END, 0) * CASE WHEN spec_l.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            COALESCE(CASE WHEN spec_r.specificity_score IS NOT NULL THEN spec_r.specificity_score ELSE NULL END, 0) * CASE WHEN spec_r.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            COALESCE(CASE WHEN r.EM IS NOT NULL AND LENGTH(TRIM(COALESCE(r.EM, ''))) > 0 AND spec_e.specificity_score IS NOT NULL THEN spec_e.specificity_score ELSE NULL END, 0) * CASE WHEN r.EM IS NOT NULL AND LENGTH(TRIM(COALESCE(r.EM, ''))) > 0 AND spec_e.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            COALESCE(CASE WHEN r.Target IS NOT NULL AND LENGTH(TRIM(COALESCE(r.Target, ''))) > 0 AND spec_t.specificity_score IS NOT NULL THEN spec_t.specificity_score ELSE NULL END, 0) * CASE WHEN r.Target IS NOT NULL AND LENGTH(TRIM(COALESCE(r.Target, ''))) > 0 AND spec_t.specificity_score IS NOT NULL THEN 1 ELSE 0 END
        ) / NULLIF(
            CASE WHEN spec_l.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN spec_r.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN r.EM IS NOT NULL AND LENGTH(TRIM(COALESCE(r.EM, ''))) > 0 AND spec_e.specificity_score IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN r.Target IS NOT NULL AND LENGTH(TRIM(COALESCE(r.Target, ''))) > 0 AND spec_t.specificity_score IS NOT NULL THEN 1 ELSE 0 END,
            0
        )"""
            spec_joins = """
    LEFT JOIN spec AS spec_l ON UPPER(r.Ligand)   = spec_l.gene_upper AND r."Sender.group"   = spec_l.cell_type
    LEFT JOIN spec AS spec_r ON UPPER(r.Receptor) = spec_r.gene_upper AND r."Receiver.group" = spec_r.cell_type
    LEFT JOIN spec AS spec_e ON UPPER(r.EM)       = spec_e.gene_upper AND r."Receiver.group" = spec_e.cell_type
    LEFT JOIN spec AS spec_t ON UPPER(r.Target)   = spec_t.gene_upper AND r."Receiver.group" = spec_t.cell_type"""
        else:
            # Non-full key: position genes are aggregated; skip per-gene specificity
            mean_spec_expr = "NULL"
            spec_joins = ""

        cq += f"""
,
spec AS (
    SELECT UPPER(gene_symbol) AS gene_upper, cell_type, specificity_score
    FROM read_csv_auto('{safe_spec}')
),
cell_counts AS (
    SELECT cell_type, MIN(n_cells) AS min_cells
    FROM read_csv_auto('{safe_counts}')
    WHERE sample LIKE 'ma_%'
    GROUP BY cell_type
),
annotated AS (
    SELECT
        r.*,
        {mean_spec_expr} AS mean_gene_specificity,
        CASE
            WHEN ccs.min_cells IS NULL AND cco.min_cells IS NULL THEN NULL
            WHEN ccs.min_cells IS NULL THEN cco.min_cells
            WHEN cco.min_cells IS NULL THEN ccs.min_cells
            ELSE LEAST(ccs.min_cells, cco.min_cells)
        END::INTEGER AS min_cell_count
    FROM ranked r{spec_joins}
    LEFT JOIN cell_counts AS ccs ON r."Sender.group"   = ccs.cell_type
    LEFT JOIN cell_counts AS cco ON r."Receiver.group" = cco.cell_type
)
SELECT
    {", ".join(_q(c) for c in key_cols)},
    PDS,
    n_timepoints_present,
    n_conditions_present,
    backbone_rank,
    mean_gene_specificity,
    min_cell_count,
    is_cholinergic_target,
    conditions_present,
    contrasts_present{extra_pos_select_suffix}
FROM annotated
ORDER BY backbone_rank, "Sender.group", "Receiver.group", Ligand, Receptor, EM, Target"""

    else:
        # No annotation files: emit NULL annotation columns
        cq += f"""
SELECT
    {", ".join(_q(c) for c in key_cols)},
    PDS,
    n_timepoints_present,
    n_conditions_present,
    backbone_rank,
    NULL::DOUBLE  AS mean_gene_specificity,
    NULL::INTEGER AS min_cell_count,
    is_cholinergic_target,
    conditions_present,
    contrasts_present{extra_pos_select_suffix}
FROM ranked
ORDER BY backbone_rank, "Sender.group", "Receiver.group", Ligand, Receptor, EM, Target"""

    return cq


# ---------------------------------------------------------------------------
# Main reduction entry point
# ---------------------------------------------------------------------------

def reduce(
    wide_dir: str,
    out_path: str,
    backbone_key: str = "full",
    spec_path: str | None = None,
    counts_path: str | None = None,
    memory_limit: str = "8GB",
    verbose: bool = True,
) -> dict:
    """Run backbone reduction and write ``backbone_table.parquet``.

    Returns a summary dict with row count, peak timing, and annotation status.
    """
    if backbone_key not in _KEY_COLS:
        raise ValueError(f"backbone_key must be one of {sorted(_KEY_COLS)}; got {backbone_key!r}")

    # --- locate wide parquets --------------------------------------------
    pattern = os.path.join(wide_dir, "*_incytr_output.parquet")
    all_files = sorted(glob.glob(pattern))
    if not all_files:
        raise FileNotFoundError(f"No *_incytr_output.parquet in {wide_dir!r}")

    spill = os.environ.get(
        "DUCKDB_TEMP_DIR",
        os.path.join(os.path.expanduser("~"), ".cache", "duckdb"),
    )
    os.makedirs(spill, exist_ok=True)

    con = duckdb.connect()
    con.execute(f"PRAGMA memory_limit='{memory_limit}'")
    con.execute(f"SET temp_directory='{spill}'")

    # --- parse each file -------------------------------------------------
    files_info: list[tuple[str, str, str, str, str, str]] = []
    skipped: list[str] = []
    for fpath in all_files:
        parsed = _parse_filename(fpath)
        if parsed is None:
            skipped.append(fpath)
            continue
        contrast, condition, timepoint = parsed
        sp1, sp2 = _detect_sigprob(con, fpath)
        files_info.append((fpath, sp1, sp2, contrast, condition, timepoint))

    if not files_info:
        raise FileNotFoundError(
            f"No parseable wide parquets in {wide_dir!r}. Skipped: {skipped}"
        )
    if skipped and verbose:
        print(f"  (warn) skipped {len(skipped)} unparseable files: {skipped}", flush=True)

    if verbose:
        print(f"  backbone_key={backbone_key!r}  files={len(files_info)}  "
              f"spec={'present' if spec_path else 'absent'}  "
              f"counts={'present' if counts_path else 'absent'}", flush=True)
        for abs_path, sp1, sp2, contrast, condition, timepoint in files_info:
            print(f"    {os.path.basename(abs_path):55s}  "
                  f"contrast={contrast}  condition={condition}  timepoint={timepoint}",
                  flush=True)

    # --- resolve annotation files ----------------------------------------
    resolved_spec = spec_path if (spec_path and os.path.isfile(spec_path)) else None
    resolved_counts = counts_path if (counts_path and os.path.isfile(counts_path)) else None
    if spec_path and not resolved_spec and verbose:
        print(f"  (warn) spec file not found: {spec_path}; mean_gene_specificity=NULL",
              flush=True)
    if counts_path and not resolved_counts and verbose:
        print(f"  (warn) counts file not found: {counts_path}; min_cell_count=NULL",
              flush=True)

    key_cols = _KEY_COLS[backbone_key]
    sql = _build_backbone_query(files_info, key_cols, resolved_spec, resolved_counts)

    if verbose:
        print(f"  running backbone reduction query (DuckDB {duckdb.__version__})...",
              flush=True)

    t0 = time.perf_counter()
    result = con.execute(sql).arrow()
    elapsed = time.perf_counter() - t0

    n_rows = result.num_rows
    if verbose:
        print(f"  reduction done: {n_rows:,} backbone paths in {elapsed:.1f}s", flush=True)

    # --- write output (atomic .tmp + rename) -----------------------------
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    tmp_path = out_path + ".tmp"
    import pyarrow.parquet as pq
    pq.write_table(result, tmp_path, compression="snappy")
    os.replace(tmp_path, out_path)

    if verbose:
        import os as _os
        sz = _os.path.getsize(out_path)
        print(f"  written: {out_path}  ({sz / 1024:.1f} KB)", flush=True)

    return {
        "n_backbone_paths": n_rows,
        "n_contrasts_input": len(files_info),
        "backbone_key": backbone_key,
        "annotation_spec": resolved_spec is not None,
        "annotation_counts": resolved_counts is not None,
        "elapsed_s": round(elapsed, 2),
        "out_path": out_path,
    }


# ---------------------------------------------------------------------------
# Verification helpers (light, in-memory on the already-small output)
# ---------------------------------------------------------------------------

def verify(out_path: str, wide_dir: str, verbose: bool = True) -> bool:
    """Run light sanity checks on the backbone table.

    Returns True if all checks pass, False otherwise.
    """
    import pyarrow.parquet as pq

    tbl = pq.read_table(out_path)
    df = tbl.to_pandas()
    ok = True

    def _fail(msg: str) -> None:
        nonlocal ok
        ok = False
        print(f"  FAIL: {msg}", flush=True)

    def _pass(msg: str) -> None:
        print(f"  OK:   {msg}", flush=True)

    n = len(df)
    if verbose:
        print(f"  rows: {n:,}", flush=True)

    # 1. n_timepoints_present / n_conditions_present in [1, 3]
    for col in ("n_timepoints_present", "n_conditions_present"):
        if col in df.columns:
            mn, mx = int(df[col].min()), int(df[col].max())
            if mn < 1 or mx > 3:
                _fail(f"{col} out of range [1,3]: min={mn}, max={mx}")
            else:
                _pass(f"{col} in [1,3]: min={mn}, max={mx}")

    # 2. backbone_rank is dense (consecutive integers starting at 1)
    if "backbone_rank" in df.columns:
        ranks = sorted(df["backbone_rank"].unique())
        expected = list(range(1, len(ranks) + 1))
        if ranks != expected:
            _fail(f"backbone_rank not dense: {ranks[:10]}...")
        else:
            _pass(f"backbone_rank dense: 1..{max(ranks)}")

    # 3. Backbone rows ≤ distinct 6-tuples in wide/ (can be equal or fewer
    #    depending on backbone_key; equal for 'full' key)
    con = duckdb.connect()
    spill = os.environ.get(
        "DUCKDB_TEMP_DIR",
        os.path.join(os.path.expanduser("~"), ".cache", "duckdb"),
    )
    con.execute(f"SET temp_directory='{spill}'")
    pattern = os.path.join(wide_dir, "*_incytr_output.parquet")
    try:
        raw_n = con.execute(
            f"""SELECT COUNT(DISTINCT ("Sender.group", "Receiver.group",
                                       Ligand, Receptor, EM, Target))
                FROM read_parquet('{pattern}', union_by_name=true)"""
        ).fetchone()[0]
        if n <= raw_n:
            _pass(f"backbone rows ({n:,}) ≤ raw distinct 6-tuples ({raw_n:,})")
        else:
            _fail(f"backbone rows ({n:,}) > raw distinct 6-tuples ({raw_n:,})")
    except Exception as exc:
        print(f"  (warn) could not check raw wide row count: {exc}", flush=True)

    # 4. is_cholinergic_target always True when Receiver.group == Cholinergic.Neurons
    if "is_cholinergic_target" in df.columns and "Receiver.group" in df.columns:
        chol = df[df["Receiver.group"] == "Cholinergic.Neurons"]
        if len(chol) > 0:
            if chol["is_cholinergic_target"].all():
                _pass(f"is_cholinergic_target=True for all {len(chol):,} Cholinergic.Neurons rows")
            else:
                _fail("is_cholinergic_target=False for some Cholinergic.Neurons rows")
            # Also confirm they are PRESENT (not dropped)
            _pass(f"Cholinergic.Neurons paths present: {len(chol):,} (not dropped)")
        else:
            print("  (info) no Cholinergic.Neurons rows in backbone", flush=True)

    return ok


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _default_paths() -> tuple[str, str, str, str]:
    repo = str(_REPO_ROOT)
    wide_dir = os.path.join(repo, "outputs", "reports", "incytr_pair_mode", "wide")
    out_path = os.path.join(repo, "outputs", "reports", "incytr_pair_mode",
                            "backbone", "backbone_table.parquet")
    spec_path = os.path.join(repo, "outputs", "reports", "snrna_integration",
                             "song_expression_specificity.csv")
    counts_path = os.path.join(repo, "outputs", "reports", "snrna_integration",
                               "pseudobulk_cell_counts.csv")
    return wide_dir, out_path, spec_path, counts_path


def main(argv: list[str] | None = None) -> None:
    wide_dir_def, out_def, spec_def, counts_def = _default_paths()

    p = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--wide-dir", default=wide_dir_def,
                   help="Directory containing *_incytr_output.parquet files "
                        f"(default: {wide_dir_def})")
    p.add_argument("--out", default=out_def,
                   help=f"Output parquet path (default: {out_def})")
    p.add_argument("--spec-path", default=spec_def,
                   help="Path to song_expression_specificity.csv "
                        f"(default: {spec_def})")
    p.add_argument("--counts-path", default=counts_def,
                   help="Path to pseudobulk_cell_counts.csv "
                        f"(default: {counts_def})")
    p.add_argument("--backbone-key", default="full",
                   choices=list(_KEY_COLS),
                   help="Path identity key: 'full' (default, locked 6-tuple), "
                        "'l-r-em', 'r-em-t', 'r-em' (for B4/B5 W1-gate analysis)")
    p.add_argument("--memory-limit", default="8GB",
                   help="DuckDB memory limit (default: 8GB)")
    p.add_argument("--verify", action="store_true",
                   help="Run sanity checks on the output after writing")
    p.add_argument("--quiet", action="store_true",
                   help="Suppress progress output")
    args = p.parse_args(argv)

    verbose = not args.quiet
    if verbose:
        print("=== backbone_reduction.py ===", flush=True)

    summary = reduce(
        wide_dir=args.wide_dir,
        out_path=args.out,
        backbone_key=args.backbone_key,
        spec_path=args.spec_path,
        counts_path=args.counts_path,
        memory_limit=args.memory_limit,
        verbose=verbose,
    )

    if verbose:
        print(f"\n  Summary:", flush=True)
        for k, v in summary.items():
            print(f"    {k}: {v}", flush=True)

    if args.verify:
        print("\n  Running verification...", flush=True)
        ok = verify(args.out, args.wide_dir, verbose=verbose)
        if not ok:
            print("\n  VERIFICATION FAILED", flush=True)
            sys.exit(1)
        print("\n  Verification passed.", flush=True)

    if verbose:
        print("\n=== done ===", flush=True)


if __name__ == "__main__":
    main()
